### ISSUE TITLE
Invalid IRI for @base

### ISSUE THREAD

**Issue by smpadhy** [incf-nidash/dicom-ontology#8]
Invalid IRI is being shown at this line 14: @base <http://www.w3.org/2002/07/owl#>
It is without "#".

**Comment by khelm** [comment]
Thanks @smpadhy for raising this issue.  I just checked the NIDM-Results owl file and that contains a ` @base http://www.w3.org/2002/07/owl#` statement that also has the '#' at the end. @cmaumet can you comment?

**Comment by smpadhy** [comment]
Though it protege, it is not showing any error with or without '#' in the end of the '@base'. I am getting this when I upload to rdfstore_min.js.

For nidm-results.owl file I have deleted the '#' in my local copy for nidm-term-search app. 
Here is the error I am getting with '#' at the end of '@base'.

Error: Invalid base IRI http://www.w3.org/2002/07/owl# at line 14.
    at m._error (rdfstore_min.js:325)
    at m._readBaseIRI (rdfstore_min.js:324)
    at rdfstore_min.js:328
    at m._tokenizeToEnd (rdfstore_min.js:304)
    at rdfstore_min.js:305

**Comment by smpadhy** [comment]
Here is a pending pull request from @satra : https://github.com/incf-nidash/nidm/pull/417 and has corresponding discussions with @cmaumet

**Comment by cmaumet** [comment]
@smpadhy, @khelm: According to https://www.w3.org/TR/2004/REC-owl-guide-20040210/#Namespaces the `owl` prefix has a final `#`.

I think the issue with base not accepting `#` is an implementation problem. RDFlib use to have this problem as well: reported by @satra in https://github.com/RDFLib/rdflib/issues/379 and fixed in https://github.com/RDFLib/rdflib/pull/407.

**Comment by khelm** [comment]
Par of the previous discussion was to remove the ` @base http://www.w3.org/2002/07/owl#` statement from the OWL file.  Is that still being considered?

**Comment by cmaumet** [comment]
@khelm: Sure removing `base` is fine as a workaround (though the original owl file is correct). If we remove `base`, we will have to double check that no term was defined using the implicit `base` prefix but rather using the `owl:` prefix explicitely. 

The other way to go around this is to edit the owl file on-the-fly before loading it with the tool that can't handle the `#` in base. An example of this is available in the `nidmresults` codebase: https://github.com/incf-nidash/nidmresults/blob/5660815af5b14d9d63b2df82137ed941f9ad3de8/nidmresults/test/check_consistency.py#L152-L158.

Does that make sense for you both?

**Comment by khelm** [comment]
@cmaumet I believe that I only use explicit calls to owl terms (e.g. `owl:sameAs`) so removing the base statement should be ok for the dicom file. I would think though that we would want all of the files to be consistent and either have it or not. I guess it depends on how much of a problem this will cause as people try to use these files with packages that don't support '#' in base statements.

**Comment by khelm** [comment]
I've removed the base statement from the owl file and verified that it still opens without errors in Protege.  I will therefore close this issue.

**Comment by smpadhy** [comment]
Thank you.
